name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # Claude will post results back to PR
      issues: write          # Allow commenting on issues/PRs
      id-token: write
      actions: read          # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Detect Claude Command
        id: detect
        run: |
          body="${{ github.event.comment.body || github.event.review.body }}"
          echo "Comment body: $body"
          if [[ "$body" == *"@claude review"* ]]; then
            echo "command=review" >> $GITHUB_OUTPUT
          elif [[ "$body" == *"@claude suggest"* ]]; then
            echo "command=suggest" >> $GITHUB_OUTPUT
          elif [[ "$body" == *"@claude implement"* ]]; then
            echo "command=implement" >> $GITHUB_OUTPUT
          elif [[ "$body" == *"@claude security-review"* ]]; then
            echo "command=security-review" >> $GITHUB_OUTPUT
          else
            echo "command=review" >> $GITHUB_OUTPUT # fallback
          fi

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          command: ${{ steps.detect.outputs.command }}
          additional_permissions: |
            actions: read
