name: remove-label.yml

on:
  pull_request:
    types: [labeled]

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Remove label
        run: |
          gh issue edit ${{ github.event.number }} --remove-label "bug,enhancement"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
