name: remove-label.yml

on:
  pull_request:
    types: [labeled]

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        run: |
          echo "${{ github.token }}" | gh auth login --with-token

      - name: Remove label
        run: |
          gh issue edit ${{ github.event.number }} --remove-label "bug"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
